name: Test-And-Analyze

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: file_changes
        uses: tj-actions/changed-files@v45
        with:
          files: |
            src/**

        #   files: |
        #     *.component.html
        #     *.container.html
        #     *.component.ts
        #     **.ts

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11'
      
      - name: Install dependencies
        run: npm install
      
      - name: Lint
        # if: steps.file_changes.outputs.test_any_changed == 'true'  
        run: |
            INPUT_STRING="${{ steps.file_changes.outputs.all_changed_files }}"
            OUTPUT=""

            echo $INPUT_STRING
            
            for FILE in $INPUT_STRING; do
              OUTPUT="$OUTPUT --lint-file-patterns $FILE"
            done

            OUTPUT="${OUTPUT# }"
            echo "args=$OUTPUT" >> $GITHUB_OUTPUT

            npm run lint -- $OUTPUT
